"""Default HyrCap training and evaluation configuration."""

import os


config = {
    "data_root": os.environ.get("HYRCAP_DATA_ROOT", "data/thumos14"),
    "annotations": "annotations.json",
    "intern_features": "features/feature_internvideo2_6b",
    "vjepa_features": "features/feature_vjepa",
    "seed": 43,
    "cpu_threads": 4,
    "default_fps": 30,
    "base_frame": 16,
    "stride": 4,
    "feature_dim": 11648,
    "modality_dims": [3200, 8448],
    "hidden_dim": 512,
    "num_classes": 20,
    "num_feature_levels": 6,
    "num_sampling_levels": 6,
    "n_heads": 8,
    "n_deform_heads": 8,
    "enc_layers": 6,
    "dec_layers": 6,
    "dim_feedforward": 2048,
    "gc_kernel_size": 11,
    "dc_level": 2,
    "group_conv": False,
    "base_scale": 32,
    "max_queries": 900,
    "fix_encoder_proposals": True,
    "dec_n_points": 4,
    "length_ratio": -1,
    "temperature": 10000,
    "query_selection_ratio": 0.5,
    "enc_dropout": 0.0,
    "dec_dropout": 0.0,
    "attn_dropout": 0.0,
    "transformer_activation": "relu",
    "emb_dropout": 0.0,
    "use_concat_residual": True,
    "duration_thresh": 0.05,
    "iou_range": [0.3, 0.4, 0.5, 0.6, 0.7],
    "min_score": 0.001,
    "nms_thr": 0.7,
    "eval_topk": 900,
    "max_seq_len": 4096,
    "set_cost_class": 2.0,
    "set_cost_iou": 2.0,
    "cls_loss_coef": 2.0,
    "iou_loss_coef": 2.0,
    "focal_alpha": 0.25,
    "detector_training": {
        "lr": 5e-5,
        "lr_backbone": 1e-5,
        "weight_decay": 0.0,
        "batch_size": 2,
        "num_workers": 6,
        "sampling": "historical_workers",
        "historical_eval_seed_draws": 2,
        "epochs": 80,
        "lr_drop": 80,
        "lr_gamma": 0.1,
        "clip_max_norm": 0.1,
        "save_interval": 10,
        "use_ema": True,
        "ema_decay": 0.999,
        "recovery_interval": 20,
    },
    "calibration_training": {
        "lr": 0.003,
        "threshold": 0.5,
        "hidden": 64,
        "dropout": 0.1,
        "weight_decay": 1e-4,
        "batch_size": 8,
        "seed": 42,
        "epochs": 50,
    },
    "calibration_scoring": {
        "cpcc_beta": 0.15,
        "lqe_gamma": 1.0,
        "prs_gamma": 0.5,
    },
}
